### ISSUE TITLE
IDE is for the weak therefore use nano

### ISSUE THREAD

**Issue by somebody1234** [douglasselias/uccm#1]

**Comment by douglasselias** [comment]
Interesting choice but I still prefer a editor with a graphical interface. I was just kidding about the IDE. Should I remove that part? Did I look arrogant?
Changing subject, how you discovered my repo? Because it's just a simple random starless and forkless repo.

**Comment by somebody1234** [comment]
Nah it's fine :P just I _think?_ VS Code is still kinda an IDE although it has fewer features. I discovered this by looking at Charcoal's stargazers lol

**Comment by douglasselias** [comment]
Yes that's true. I saw here, I am one of the firsts to show up in the list of stargazers. So I will keep stargazing to be more noticed :smile:
